spring:
  application:
    name: mdcUser
  data:
    mongodb:
      uri: mongodb://medicADM:Pa$$wor@ds163656.mlab.com:63656/medic
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

server:
  port: ${PORT:8080}

monox:
  enabled: false
  validation:
    messages:classpath:error

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.peer.one:8050/eureka,http://http://eureka.peer.two:8060/eureka
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true


