spring:
  application:
    name: mdcUser
  data:
    mongodb:
      uri:mongodb://medic:Pa$$wor@ds163656.mlab.com:63656/medic
  jackson:
    #date-format: dd-MM-yyyy HH:mm:ss
    date-format=com.fasterxml.jackson.databind.util.ISO8601DateFormat

    

server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.peer.one:8050/eureka,http://http://eureka.peer.two:8060/eureka
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true


